### ISSUE TITLE
Does not handle `?` syntax properly

### ISSUE THREAD

**Issue by taktoa** [justinwoo/format-nix#7]
If you take a file like this one:

```
{ foo ? "foo", bar ? "bar" }:
foo + bar
```

and run it through `format-nix`, you get

```
{ foo ? "foo" bar ? "bar" }:

foo + bar
```

Note the missing `,` between the `foo` and `bar`. This makes it syntactically invalid.

**Comment by justinwoo** [comment]
https://github.com/justinwoo/format-nix/blob/db288d97a9018a50d3be63f8b20aa15e3dd45d0b/src/FormatNix.purs#L337

Formals need to be intercalated by a comma
